# Импорт библиотек

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

<img src='https://drive.google.com/uc?export=view&id=1q1pSMnZVVhVeE9l2zGckBCF33BS2vKBd'>

# Загрузка данных

In [2]:
df = pd.read_csv('../input/finalcsv/final.csv')

In [3]:
df

store  dayofweek        date  sales  customers  open  promo  \
0            1          3  2018-01-01   5530        668     1      0   
1            2          3  2018-01-01   4422        650     1      0   
2            3          3  2018-01-01   6823        805     1      0   
3            4          3  2018-01-01   9941       1429     1      0   
4            5          3  2018-01-01   4253        577     1      0   
...        ...        ...         ...    ...        ...   ...    ...   
1016090   1111          5  2020-07-29   5723        422     1      1   
1016091   1112          5  2020-07-29   9626        767     1      1   
1016092   1113          5  2020-07-29   7289        720     1      1   
1016093   1114          5  2020-07-29  27508       3745     1      1   
1016094   1115          5  2020-07-29   8680        538     1      1   

               lat        lon  
0        55.682829  37.416212  
1        55.686410  37.415503  
2        55.885081  37.476452  
3        55.711356  37.389027  
4        55.902867  37.609132  
...            ...        ...  
1016090  55.878577  37.706292  
1016091  55.791374  37.823187  
1016092  55.756921  37.824353  
1016093  55.798922  37.822139  
1016094  55.582867  37.653329  

[1016095 rows x 9 columns]

- store - магазин
- dayofweek - день недели
- date - дата
- sales - продажи
- customers - клиенты
- open - открыт магазин или нет
- promo - была ли промо акция
- lat - широта
- lon - долгота

# Делаем прогноз на июль 2020 года

<img src='https://drive.google.com/uc?export=view&id=1lkMiS2f-f-DwrBkEQIEp3HBxKm2Im9zX'>

In [4]:
df_train = df[df['date'] < '2020-07-01']
df_test = df[df['date'] >= '2020-07-01']

In [5]:
df_train

store  dayofweek        date  sales  customers  open  promo  \
0           1          3  2018-01-01   5530        668     1      0   
1           2          3  2018-01-01   4422        650     1      0   
2           3          3  2018-01-01   6823        805     1      0   
3           4          3  2018-01-01   9941       1429     1      0   
4           5          3  2018-01-01   4253        577     1      0   
...       ...        ...         ...    ...        ...   ...    ...   
983755   1111          4  2020-06-30   3945        329     1      1   
983756   1112          4  2020-06-30   7447        577     1      1   
983757   1113          4  2020-06-30   7932        793     1      1   
983758   1114          4  2020-06-30  24898       3784     1      1   
983759   1115          4  2020-06-30   6858        452     1      1   

              lat        lon  
0       55.682829  37.416212  
1       55.686410  37.415503  
2       55.885081  37.476452  
3       55.711356  37.389027  
4       55.902867  37.609132  
...           ...        ...  
983755  55.878577  37.706292  
983756  55.791374  37.823187  
983757  55.756921  37.824353  
983758  55.798922  37.822139  
983759  55.582867  37.653329  

[983760 rows x 9 columns]

In [6]:
df_test

store  dayofweek        date  sales  customers  open  promo  \
983760       1          5  2020-07-01   4665        538     1      1   
983761       2          5  2020-07-01   4838       1029     1      1   
983762       3          5  2020-07-01   8149        742     1      1   
983763       4          5  2020-07-01  11543       1395     1      1   
983764       5          5  2020-07-01   4475        527     1      1   
...        ...        ...         ...    ...        ...   ...    ...   
1016090   1111          5  2020-07-29   5723        422     1      1   
1016091   1112          5  2020-07-29   9626        767     1      1   
1016092   1113          5  2020-07-29   7289        720     1      1   
1016093   1114          5  2020-07-29  27508       3745     1      1   
1016094   1115          5  2020-07-29   8680        538     1      1   

               lat        lon  
983760   55.682829  37.416212  
983761   55.686410  37.415503  
983762   55.885081  37.476452  
983763   55.711356  37.389027  
983764   55.902867  37.609132  
...            ...        ...  
1016090  55.878577  37.706292  
1016091  55.791374  37.823187  
1016092  55.756921  37.824353  
1016093  55.798922  37.822139  
1016094  55.582867  37.653329  

[32335 rows x 9 columns]

# Возьмём несколько признаков

In [7]:
features = [
    'store',
    'dayofweek',
    'customers',
    'open',
    'promo',
]

target = ['sales']

In [8]:
X_train = df_train[features]
y_train = df_train[target]

X_test = df_test[features]
y_test = df_test[target]

In [9]:
X_train

store  dayofweek  customers  open  promo
0           1          3        668     1      0
1           2          3        650     1      0
2           3          3        805     1      0
3           4          3       1429     1      0
4           5          3        577     1      0
...       ...        ...        ...   ...    ...
983755   1111          4        329     1      1
983756   1112          4        577     1      1
983757   1113          4        793     1      1
983758   1114          4       3784     1      1
983759   1115          4        452     1      1

[983760 rows x 5 columns]

In [10]:
y_train

sales
0        5530
1        4422
2        6823
3        9941
4        4253
...       ...
983755   3945
983756   7447
983757   7932
983758  24898
983759   6858

[983760 rows x 1 columns]

# Воспользуемся простым методом прогноза

<img src='https://drive.google.com/uc?export=view&id=1alUGHx-Pabz3C3xvFDHxYbgP3tsPsH1D'>

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# Научим нашу модель

In [12]:
model.fit(
    X_train,
    y_train
)

LinearRegression()

In [13]:
coefs = model.coef_[0]
coefs

array([-1.51031308e-01, -5.55572871e+01,  6.07463705e+00,  1.67556349e+03,
        1.27110167e+03])

In [14]:
intercept = model.intercept_
intercept

array([352.11911259])

In [15]:
df_train[features].head(1)

store  dayofweek  customers  open  promo
0      1          3        668     1      0

In [16]:
1 * coefs[0] + 3 * coefs[1] + 668 * coefs[2] + 1 * coefs[3] + 0 * coefs[4] + intercept

array([5918.71726263])

In [17]:
model.predict(X_train.head(1))

array([[5918.71726263]])

In [18]:
X_train.head(1)

store  dayofweek  customers  open  promo
0      1          3        668     1      0

In [19]:
pred_train = model.predict(X_train)
pred_train

array([[ 5918.71726263],
       [ 5809.22276437],
       [ 6750.64047619],
       ...,
       [ 7725.64445989],
       [25894.73285244],
       [ 5653.89116239]])

In [20]:
train_preds = pd.DataFrame(pred_train, columns=['pred'])
train_preds['sales'] = y_train

train_preds

pred  sales
0        5918.717263   5530
1        5809.222764   4422
2        6750.640476   6823
3       10541.062966   9941
4        5365.321166   4253
...              ...    ...
983755   4907.314930   3945
983756   6413.673888   7447
983757   7725.644460   7932
983758  25894.732852  24898
983759   5653.891162   6858

[983760 rows x 2 columns]

# Сделаем прогноз

<img src='https://drive.google.com/uc?export=view&id=1YUyJxrl9ZLCGCJjSK1PvAm8IeHZU7brE'>

In [21]:
pred_test = model.predict(
    X_test
)

In [22]:
pred_test

array([[ 6289.00153871],
       [ 9271.49730015],
       [ 7527.9254348 ],
       ...,
       [ 7226.63866794],
       [25602.26472027],
       [ 6120.75266178]])

In [23]:
test_preds = pd.DataFrame(pred_test, columns=['pred'])
test_preds['sales'] = y_test.values

test_preds

pred  sales
0       6289.001539   4665
1       9271.497300   4838
2       7527.925435   8149
3      11494.512399  11543
4       6221.576406   4475
...             ...    ...
32330   5416.698889   5723
32331   7512.297641   9626
32332   7226.638668   7289
32333  25602.264720  27508
32334   6120.752662   8680

[32335 rows x 2 columns]

# Оценим точность прогноза

<img src='https://drive.google.com/uc?export=view&id=1LK0jRvKpxNar4OCCJI_XdqnYs8hxnIUU'>

$$1 - \frac{MSE}{var}$$

In [24]:
from sklearn.metrics import mean_squared_error, r2_score

print(f"Средняя квадратичная ошибка (MSE) модели на обучающей выборке {mean_squared_error(y_train, pred_train)}")
print(f"Средняя квадратичная ошибка (MSE) модели на тестовой выборке {mean_squared_error(y_test, pred_test)}")
print()
print(f"Коэффициент детерминации (R^2) модели на обучающей выборке {r2_score(y_train, pred_train)}")
print(f"Коэффициент детерминации (R^2) модели на тестовой выборке {r2_score(y_test, pred_test)}")

Средняя квадратичная ошибка (MSE) модели на обучающей выборке 2188564.092935027
Средняя квадратичная ошибка (MSE) модели на тестовой выборке 2308053.351565448

Коэффициент детерминации (R^2) модели на обучающей выборке 0.8526676817253495
Коэффициент детерминации (R^2) модели на тестовой выборке 0.8242831203993981
